//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMLEntities : DbContext
    {
        public DMLEntities()
            : base("name=DMLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Narucitelj> Narucitelj { get; set; }
        public virtual DbSet<Primatelj> Primatelj { get; set; }
        public virtual DbSet<Radiliste> Radiliste { get; set; }
        public virtual DbSet<RadniNalog> RadniNalog { get; set; }
        public virtual DbSet<RegOznaka> RegOznaka { get; set; }
        public virtual DbSet<RobuIzdao> RobuIzdao { get; set; }
        public virtual DbSet<Vozac> Vozac { get; set; }
        public virtual DbSet<VrstaRobe> VrstaRobe { get; set; }
        public virtual DbSet<VrstaUsluge> VrstaUsluge { get; set; }
    }
}
