//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMLEntities : DbContext
    {
        public DMLEntities()
            : base("name=DMLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mjera> Mjeras { get; set; }
        public virtual DbSet<Narucitelj> Naruciteljs { get; set; }
        public virtual DbSet<Primatelj> Primateljs { get; set; }
        public virtual DbSet<Radiliste> Radilistes { get; set; }
        public virtual DbSet<RadniNalog> RadniNalogs { get; set; }
        public virtual DbSet<RegOznaka> RegOznakas { get; set; }
        public virtual DbSet<RobuIzdao> RobuIzdaos { get; set; }
        public virtual DbSet<Vozac> Vozacs { get; set; }
        public virtual DbSet<VrstaRobe> VrstaRobes { get; set; }
        public virtual DbSet<VrstaUsluge> VrstaUsluges { get; set; }
    }
}
