//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMLEntities : DbContext
    {
        public DMLEntities()
            : base("name=DMLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KatalogPostavke> KatalogPostavkes { get; set; }
        public virtual DbSet<Postavke> Postavkes { get; set; }
        public virtual DbSet<RadniNalog> RadniNalogs { get; set; }
    }
}
