//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadniNalog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public int VrstaRobeId { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public int RobuIzdaoId { get; set; }
        public int RegOznakaId { get; set; }
        public int VrstaUslugeId { get; set; }
        public int RadilisteId { get; set; }
        public int VozacId { get; set; }
        public string VrstaStroja { get; set; }
        public int NaruciteljId { get; set; }
        public int PrimateljId { get; set; }
        public string RN { get; set; }
        public int MjeraId { get; set; }
    
        public virtual Mjera Mjera { get; set; }
        public virtual Narucitelj Narucitelj { get; set; }
        public virtual Primatelj Primatelj { get; set; }
        public virtual Radiliste Radiliste { get; set; }
        public virtual RegOznaka RegOznaka { get; set; }
        public virtual RobuIzdao RobuIzdao { get; set; }
        public virtual Vozac Vozac { get; set; }
        public virtual VrstaRobe VrstaRobe { get; set; }
        public virtual VrstaUsluge VrstaUsluge { get; set; }
    }
}
