//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadniNalog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string VrstaRobe { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public string Izvrstitelj { get; set; }
        public string RegOznaka { get; set; }
        public string VrstaUsluge { get; set; }
        public string Radiliste { get; set; }
        public string Vozac { get; set; }
        public string VrstaStroja { get; set; }
        public string Narucitelj { get; set; }
        public string Primatelj { get; set; }
    }
}
